//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 09 17:48:31 CEST 2015
//----------------------------------------------------

package kompilatory.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
	/* terminals */
	public static final int RIGHT_PARENTHESIS = 5;
	public static final int COMA = 9;
	public static final int INTEGER = 11;
	public static final int COLON = 8;
	public static final int LEFT_PARENTHESIS = 4;
	public static final int BOOLEAN = 10;
	public static final int NULL = 14;
	public static final int EOF = 0;
	public static final int RIGHT_BRACKET = 3;
	public static final int DOUBLE = 12;
	public static final int error = 1;
	public static final int RIGHT_SQ_BRACKET = 7;
	public static final int LEFT_BRACKET = 2;
	public static final int LEFT_SQ_BRACKET = 6;
	public static final int WORD = 13;
}
